### PR TITLE
Fix various warning issues

### LINKED ISSUE #409: Hardcoded warnings level
Hi! I use your project with CMake [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) feature because the library is not available in all Linux distibutions / vcpkg on Windows.
But you have hardcoded warnings level for [MSVC](https://github.com/stp/stp/blob/81850c0d6973bf5fb7d283ab4037385930290be2/CMakeLists.txt#L239) and [GCC](https://github.com/stp/stp/blob/master/CMakeLists.txt#L308).

Because of it I have the following warnings on GCC 11.1 in your project:

<details>
  <summary>GCC</summary>

```
build/_deps/stp-src/lib/extlib-abc/vecPtr.h|747 col 13| warning: cast between incompatible function types from «int (*)()» to «int (*)(const void*, const void*)» [-Wcast-function-type]
   747 |             (int (*)(const void *, const void *)) Vec_PtrSortCompare );
       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 build/_deps/stp-src/lib/extlib-abc/vecPtr.h: In function: «void Vec_PtrUniqify(Vec_Ptr_t*, int (*)())»:
build/_deps/stp-src/lib/extlib-abc/vecPtr.h|767 col 13| warning: cast between incompatible function types from «int (*)()» to «int (*)(const void*, const void*)» [-Wcast-function-type]
   767 |             (int (*)(const void *, const void *)) Vec_PtrSortCompare );
       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from build/_deps/stp-src/include/stp/ToSat/AIG/BBNodeManagerAIG.h:34,
 build/_deps/stp-src/lib/extlib-abc/cnf_short.h: На глобальном уровне:
build/_deps/stp-src/lib/extlib-abc/cnf_short.h|90 col 29| warning: ISO C ++ disallow zero size array «pFanins» [-Wpedantic]
    90 |     int             pFanins[0];      // the fanins (followed by the truth table)
       |                             ^
 build/_deps/stp-src/lib/Simplifier/Simplifier.cpp: In function:-члене «stp::ASTNode stp::Simplifier::simplify_term_switch(const stp::ASTNode&, stp::ASTNode&, stp::ASTNode&, stp::ASTNodeMap*, stp::Kind, unsigned int)»:
build/_deps/stp-src/lib/Simplifier/Simplifier.cpp|2037 col 5| warning: this operator may fallthrough [-Wimplicit-fallthrough=]
  2037 |     }
       |     ^
build/_deps/stp-src/lib/Simplifier/Simplifier.cpp|2041 col 5| here:
  2041 |     case BVPLUS:
       |     ^~~~
 [33/125] Building CXX object _deps/stp-build/lib/Simplifier/CMakeFiles/simplifier.dir/DifficultyScore.cpp.o
 build/_deps/stp-src/lib/Simplifier/DifficultyScore.cpp: In function: «long int stp::eval(const stp::ASTNode&)»:
build/_deps/stp-src/lib/Simplifier/DifficultyScore.cpp|57 col 22| warning: comparison of integer expressions of different signedness: «int» and «unsigned int» [-Wsign-compare]
    57 |     for (int i =1; i < b.GetValueWidth();i++)
       |                    ~~^~~~~~~~~~~~~~~~~~~
```
  
</details>

On MSVC I have the following warnings in your project:

<details>
  <summary>MSVC</summary>

```  
[build] [10/124   0% :: 0.145] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigFanout.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [11/124   1% :: 0.148] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigMffc.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [12/124   2% :: 0.155] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigObj.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [13/124   3% :: 0.158] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigCheck.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [14/124   4% :: 0.161] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigOper.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [15/124   4% :: 0.163] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigDfs.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [16/124   5% :: 0.174] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigMan.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [17/124   6% :: 0.177] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigPart.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\aig\aigPart.c(295): warning C4312: 'type cast': conversion from 'long' to 'Aig_Obj_t *' of greater size
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\aig\aigPart.c(297): warning C4312: 'type cast': conversion from 'long' to 'Aig_Obj_t *' of greater size
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\aig\aigPart.c(322): warning C4311: 'type cast': pointer truncation from 'Aig_Obj_t *' to 'long'
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\aig\aigPart.c(334): warning C4311: 'type cast': pointer truncation from 'Aig_Obj_t *' to 'long'
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\aig\aigPart.c(749): warning C4311: 'type cast': pointer truncation from 'Aig_Obj_t *' to 'long'
[build] [18/124   7% :: 0.180] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigMem.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [19/124   8% :: 0.184] Generating ASTKind.cpp, ../../include/stp/AST/ASTKind.h
[build] [20/124   8% :: 0.319] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigRepr.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [21/124   9% :: 0.323] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigScl.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\aig\aigScl.c(180): warning C4312: 'type cast': conversion from 'long' to 'Aig_Obj_t *' of greater size
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\aig\aigScl.c(183): warning C4311: 'type cast': pointer truncation from 'Aig_Obj_t *' to 'long'
[build] [22/124  10% :: 0.326] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigRet.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [23/124  11% :: 0.336] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigOrder.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [24/124  12% :: 0.348] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigSeq.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [25/124  12% :: 0.386] Building CXX object _deps\stp-build\lib\AST\CMakeFiles\AST.dir\ASTKind.cpp.obj
[build] [26/124  13% :: 0.805] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darMan.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [27/124  14% :: 0.808] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darRefact.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [28/124  15% :: 0.810] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darScript.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [29/124  16% :: 0.813] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darPrec.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [74/124  52% :: 14.794] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\kit\kitGraph.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\kit\kitGraph.c(342): warning C4312: 'type cast': conversion from 'long' to 'void *' of greater size
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\kit\kitGraph.c(347): warning C4311: 'type cast': pointer truncation from 'void *' to 'long'
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\kit\kitGraph.c(348): warning C4311: 'type cast': pointer truncation from 'void *' to 'long'
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-src\lib\extlib-abc\aig\kit\kitGraph.c(352): warning C4312: 'type cast': conversion from 'long' to 'void *' of greater size
[build] [75/124  53% :: 14.989] Generating parsesmt2.tab.cpp, parsesmt2.tab.h, lexsmt2.cpp
[build] D:/Work/FortifyIQ-win-Ninja-Debug/_deps/stp-src/lib/Parser/smt2.y: warning: 1 reduce/reduce conflict [-Wconflicts-rr]
[build] D:/Work/FortifyIQ-win-Ninja-Debug/_deps/stp-src/lib/Parser/smt2.y: note: rerun with option '-Wcounterexamples' to generate conflict counterexamples
[build] [76/124  54% :: 15.140] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\kit\kitAig.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [77/124  54% :: 15.275] Building CXX object _deps\stp-build\lib\Printer\CMakeFiles\printer.dir\dotPrinter.cpp.obj
[build] [78/124  55% :: 15.287] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigTsim.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [79/124  56% :: 15.401] Building CXX object _deps\stp-build\lib\Printer\CMakeFiles\printer.dir\GDLPrinter.cpp.obj
[build] [80/124  57% :: 15.454] Building CXX object _deps\stp-build\lib\Printer\CMakeFiles\printer.dir\LispPrinter.cpp.obj
[build] [81/124  58% :: 15.473] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigTime.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [82/124  58% :: 15.542] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigShow.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [83/124  59% :: 15.581] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigTable.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [84/124  60% :: 15.681] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigTiming.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [85/124  61% :: 15.686] Building CXX object _deps\stp-build\lib\Printer\CMakeFiles\printer.dir\SMTLIBPrinter.cpp.obj
[build] [86/124  62% :: 15.693] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigTruth.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [87/124  62% :: 15.717] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfMan.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [88/124  63% :: 15.789] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigWin.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [90/124  65% :: 15.890] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfCut.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [91/124  66% :: 15.929] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfCore.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [92/124  66% :: 15.955] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfData.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [93/124  67% :: 16.011] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darCore.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [94/124  68% :: 16.017] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\aig\aigUtil.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [95/124  69% :: 16.087] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darBalance.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [96/124  70% :: 17.304] Building CXX object _deps\stp-build\lib\Interface\CMakeFiles\cinterface.dir\c_interface.cpp.obj
[build] [97/124  70% :: 17.625] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfWrite.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [98/124  71% :: 17.807] Building CXX object _deps\stp-build\lib\Parser\CMakeFiles\parser.dir\LetMgr.cpp.obj
[build] [99/124  72% :: 18.059] Building CXX object _deps\stp-build\lib\Interface\CMakeFiles\cppinterface.dir\cpp_interface.cpp.obj
[build] [100/124  73% :: 18.233] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfMap.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [101/124  74% :: 18.373] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfUtil.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [102/124  75% :: 18.507] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\cnf\cnfPost.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [103/124  75% :: 18.966] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darCut.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [104/124  76% :: 19.081] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darData.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [105/124  77% :: 19.120] Building CXX object _deps\stp-build\lib\Parser\CMakeFiles\parser.dir\lexcvc.cpp.obj
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(49): warning C4005: 'INT8_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(318): note: see previous definition of 'INT8_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(50): warning C4005: 'INT16_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(321): note: see previous definition of 'INT16_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(51): warning C4005: 'INT32_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(324): note: see previous definition of 'INT32_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(53): warning C4005: 'INT8_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(327): note: see previous definition of 'INT8_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(54): warning C4005: 'INT16_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(330): note: see previous definition of 'INT16_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(55): warning C4005: 'INT32_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(333): note: see previous definition of 'INT32_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(57): warning C4005: 'UINT8_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(336): note: see previous definition of 'UINT8_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(58): warning C4005: 'UINT16_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(339): note: see previous definition of 'UINT16_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(59): warning C4005: 'UINT32_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexcvc.cpp(342): note: see previous definition of 'UINT32_MAX'
[build] [106/124  78% :: 19.123] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\dar\darLib.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [107/124  79% :: 19.161] Building CXX object _deps\stp-build\lib\Parser\CMakeFiles\parser.dir\lexsmt.cpp.obj
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(49): warning C4005: 'INT8_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(318): note: see previous definition of 'INT8_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(50): warning C4005: 'INT16_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(321): note: see previous definition of 'INT16_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(51): warning C4005: 'INT32_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(324): note: see previous definition of 'INT32_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(53): warning C4005: 'INT8_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(327): note: see previous definition of 'INT8_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(54): warning C4005: 'INT16_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(330): note: see previous definition of 'INT16_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(55): warning C4005: 'INT32_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(333): note: see previous definition of 'INT32_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(57): warning C4005: 'UINT8_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(336): note: see previous definition of 'UINT8_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(58): warning C4005: 'UINT16_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(339): note: see previous definition of 'UINT16_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(59): warning C4005: 'UINT32_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt.cpp(342): note: see previous definition of 'UINT32_MAX'
[build] [108/124  79% :: 19.369] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\kit\kitSop.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [109/124  80% :: 19.433] Building CXX object _deps\stp-build\lib\Parser\CMakeFiles\parser.dir\parsesmt2.tab.cpp.obj
[build] [110/124  81% :: 19.447] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\kit\kitIsop.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] [111/124  82% :: 19.471] Building C object _deps\stp-build\lib\extlib-abc\CMakeFiles\abc.dir\aig\kit\kitTruth.c.obj
[build] cl : Command line warning D9025 : overriding '/W3' with '/W1'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(49): warning C4005: 'INT8_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(318): note: see previous definition of 'INT8_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(50): warning C4005: 'INT16_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(321): note: see previous definition of 'INT16_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(51): warning C4005: 'INT32_MIN': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(324): note: see previous definition of 'INT32_MIN'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(53): warning C4005: 'INT8_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(327): note: see previous definition of 'INT8_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(54): warning C4005: 'INT16_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(330): note: see previous definition of 'INT16_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(55): warning C4005: 'INT32_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(333): note: see previous definition of 'INT32_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(57): warning C4005: 'UINT8_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(336): note: see previous definition of 'UINT8_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(58): warning C4005: 'UINT16_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(339): note: see previous definition of 'UINT16_MAX'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\stdint.h(59): warning C4005: 'UINT32_MAX': macro redefinition
[build] D:\Work\FortifyIQ-win-Ninja-Debug\_deps\stp-build\lib\Parser\lexsmt2.cpp(342): note: see previous definition of 'UINT32_MAX'
```
  
</details>

This is because you can't just use `add_compile_options` to set warnings level on MSVC. You should replace the default warning level `/W3`. See [this](https://gitlab.kitware.com/cmake/cmake/-/issues/19084) issue for details.

Also you are using `add_compile_options` which does this globally. I would suggest to use `target_compile_options`.
But as for the level of warnings - I would suggest moving them to CI. Because it is otherwise impossible to disable warnings in your project when using `FetchContent` without patching your project. If you like the idea - I will send a PR.

### PR DESCRIPTION
**Pull request by Shatur**
This PR fixes some warnings (except for some warnings coming from ABC, which should be fixed on the ABC side, and some warnings can't be fixed properly without C++17), slightly modernizes CMake and adds the ability to suppress warnings at all.

Each commit is a separate edit.

Closes #409.

### CODE REVIEW

File: lib/STPManager/STPManager.cpp [hunk 1]
```diff
@@ -208,12 +208,12 @@ ASTNode STPMgr::CreateBVConst(unsigned int width,
...
   // track of the number of chunks copied so far
 
-  const int shift_amount = sizeof(unsigned long) * 8;
+  constexpr int shift_amount = sizeof(unsigned long) * 8;
   while (copied + shift_amount < width)
   {
     CONSTANTBV::BitVector_Chunk_Store(CreateBVConstVal, shift_amount, copied,
                                       c_val);
-    if (shift_amount < (sizeof(bvconst) * 8))
+    if constexpr (shift_amount < (sizeof(bvconst) * 8))
```
Comment (Shatur) [inline lib/STPManager/STPManager.cpp:216]: Now checked at compile time to avoid warning that `bvconst` size is less then `shift_amount` number.

File: CMakeLists.txt [hunk 2]
```diff
@@ -140,7 +152,7 @@ endif()
 
 if (NOT BUILD_SHARED_LIBS)
     if (NOT MSVC)
-        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -static ")
+        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -Wl,--whole-archive -Wl,--no-whole-archive -static ")
```
Comment (andrewvaughanj) [inline CMakeLists.txt:155]: Why is this change necessary? What happens if you link against CMS and want to use CMS's threads? Does STP need to link against `pthread`?

If you want this change, please put it in a separate PR.

File: CMakeLists.txt [hunk 3]
```diff
@@ -181,9 +193,10 @@ else ()
     endif()
 endif()
 
+option(SUPRESS_WARNINGS "Silence all warnings" OFF)
+
 if (NOT MSVC)
     add_compile_options( -g)
-    add_compile_options( -pthread )
```
Comment (andrewvaughanj) [inline CMakeLists.txt:186]: As above, I don't think this change is needed right now.

File: CMakeLists.txt [hunk 4]
```diff
@@ -181,9 +193,10 @@ else ()
     endif()
 endif()
 
+option(SUPRESS_WARNINGS "Silence all warnings" OFF)
```
Comment (andrewvaughanj) [inline CMakeLists.txt:196]: Suppress is double-P.

File: CMakeLists.txt [hunk 5]
```diff
@@ -447,7 +470,7 @@ if (NOT NOCRYPTOMINISAT)
     message(STATUS "CryptoMiniSat5 include dirs: ${CRYPTOMINISAT5_INCLUDE_DIRS}")
     add_definitions(-DUSE_CRYPTOMINISAT)
     set(USE_CRYPTOMINISAT ON)
-  else()
+  elseif(NOT SUPRESS_WARNINGS)
```
Comment (andrewvaughanj) [inline CMakeLists.txt:473]: Okay, so we were trying to address *compiler* warnings, not CMake `messages` -- why do you care about turning-off CMake messages?

File: CMakeLists.txt [hunk 6]
```diff
@@ -620,7 +643,7 @@ if ((NOT DEFINED ENABLE_PYTHON_INTERFACE) OR ENABLE_PYTHON_INTERFACE)
     if (PYTHON_EXECUTABLE)
         set(PYTHON_OK ON)
         message(STATUS "OK, found python interpreter")
-    else()
+      elseif(NOT SUPRESS_WARNINGS)
```
Comment (andrewvaughanj) [inline CMakeLists.txt:646]: Same; why do you care about CMake warnings?

File: lib/Sat/CryptoMinisat5.cpp [hunk 7]
```diff
@@ -169,7 +169,7 @@ uint32_t CryptoMiniSat5::getFixedCountWithAssumptions(const stp::SATSolver::vec_
 
   //std::cerr << assumps.size() << " assumptions" << std::endl;
 
-  unsigned assigned = 0;
+  int assigned = 0;
```
Comment (andrewvaughanj) [inline lib/Sat/CryptoMinisat5.cpp:172]: This change isn't right, as `assigned` can never be negative.

Is it `assigned >= assumps.size()` that's warning?

File: lib/Simplifier/DifficultyScore.cpp [hunk 8]
```diff
@@ -54,7 +54,7 @@ long eval(const ASTNode& b)
     const auto cbv = b[0].GetBVConst(); // cleanup?
     bool last = CONSTANTBV::BitVector_bit_test(cbv,0);
     int changes = 0;
-    for (int i =1; i < b.GetValueWidth();i++)
+    for (unsigned i =1; i < b.GetValueWidth();i++)
```
Comment (andrewvaughanj) [inline lib/Simplifier/DifficultyScore.cpp:57]: This should be `unsigned int` not "bare" `unsigned`.

**Review by andrewvaughanj — CHANGES_REQUESTED** [review]
Seems like a good first attempt; some minor comments just to clean some edges up.

File: CMakeLists.txt (hunk 2 above)
Comment (Shatur) [reply CMakeLists.txt:155]: I don't need this change, just noticed that you have extra linkage parameter that not needed at all.

File: CMakeLists.txt (hunk 3 above)
Comment (Shatur) [reply CMakeLists.txt:186]: Okay, will revert.

File: CMakeLists.txt (hunk 4 above)
Comment (Shatur) [reply CMakeLists.txt:196]: Oops, typo :)

File: CMakeLists.txt (hunk 5 above)
Comment (Shatur) [reply CMakeLists.txt:473]: If I add the project via FetchContent, I will see strange warnings from your library. For example "Testing is disabled". But in my project testing is enabled. It just confusing for developers.
I would either modernize the messages (it shouldn't be done like this) or add the option to suppress them.

File: CMakeLists.txt (hunk 2 above)
Comment (andrewvaughanj) [reply CMakeLists.txt:155]: Yeah, I'm really not sure about this; I'm just being cautious in making only the changes that you need to get your build working.

File: lib/Sat/CryptoMinisat5.cpp (hunk 7 above)
Comment (Shatur) [reply lib/Sat/CryptoMinisat5.cpp:172]: Yes, because `assumps.size()` can't be negative. I can cast `assigned`, but it compared with integer in any way. So using `unsigned` doesn't make sense to me.

File: lib/Simplifier/DifficultyScore.cpp (hunk 8 above)
Comment (Shatur) [reply lib/Simplifier/DifficultyScore.cpp:57]: Ok! But why? You using "bare" `unsigned` literally in the suggestion above.

File: CMakeLists.txt (hunk 5 above)
Comment (andrewvaughanj) [reply CMakeLists.txt:473]: > I would either modernize the messages (it shouldn't be done like this)
>

How are you proposing it should be done?

File: lib/Sat/CryptoMinisat5.cpp (hunk 7 above)
Comment (andrewvaughanj) [reply lib/Sat/CryptoMinisat5.cpp:172]: Cast the result of `assumps.size()` to `unsigned int`.

File: lib/Simplifier/DifficultyScore.cpp (hunk 8 above)
Comment (andrewvaughanj) [reply lib/Simplifier/DifficultyScore.cpp:57]: No, I didn't "add" it ... the code is currently wrong and shouldn't use bare `unsigned` and should use `unsigned int`. When you're touching code, we can make it better; if you're not touching some bit of code, just leave it alone (even if it is wrong).

Comment (andrewvaughanj) [reply lib/Simplifier/DifficultyScore.cpp:57]: "wrong" in this case is "can be improved", but minimal PRs are a lot easier to make and are more sensible.

File: CMakeLists.txt (hunk 5 above)
Comment (Shatur) [reply CMakeLists.txt:473]: How about [FeatureSummary](https://cmake.org/cmake/help/latest/module/FeatureSummary.html)?

File: lib/Simplifier/DifficultyScore.cpp (hunk 8 above)
Comment (Shatur) [reply lib/Simplifier/DifficultyScore.cpp:57]: Got it, will fix!

File: CMakeLists.txt (hunk 5 above)
Comment (andrewvaughanj) [reply CMakeLists.txt:473]: If you're happy to do this, it seems like a *great* addition!

For now, can we not do the above (i.e., silencing the CMake warnings) in this PR?

Comment (Shatur) [reply CMakeLists.txt:473]: > If you're happy to do this, it seems like a great addition!

Yes, I already working on it.

> For now, can we not do the above (i.e., silencing the CMake warnings) in this PR?

Do you want me to send a separate PR for it?

Comment (andrewvaughanj) [reply CMakeLists.txt:473]: > Do you want me to send a separate PR for it?

I would say "yes", because it makes my work easier (it is easier to review and merge smaller, self-contained PRs).

However, if merging this PR is "useless" to you without having `FeatureSummary`, then it likely needs to go in this one.

Or, we finish this one, merge it knowing the job is only half-done, and then merge the `FeatureSummary` one later on. I like this least because there's a chance you never make the second PR, leaving things in an "inconsistent" state.

I should say one thing: I'd rather **not** merge the PR that suppresses the CMake warnings. So either we back-out the change this comment is about, or you need to do the `FeatureSummary` bit.

Comment (Shatur) [reply CMakeLists.txt:473]: > I would say "yes", because it makes my work easier (it is easier to review and merge smaller, self-contained PRs).

If it easier for you - will do this way.

**Comment by Shatur** [comment]
@andrewvaughanj Thanks! I applied all discussed suggestions.

File: lib/Sat/CryptoMinisat5.cpp [hunk 9]
```diff
@@ -169,7 +169,7 @@ uint32_t CryptoMiniSat5::getFixedCountWithAssumptions(const stp::SATSolver::vec_
 
   //std::cerr << assumps.size() << " assumptions" << std::endl;
 
-  unsigned assigned = 0;
+  uint32_t assigned = 0;
```
Comment (andrewvaughanj) [inline lib/Sat/CryptoMinisat5.cpp:172]: For consistency with the rest of the code, I'd make this `unsigned int` (adding `uint32_t` makes it seem like we really know it is 32-bit limited).

File: lib/Sat/CryptoMinisat5.cpp [hunk 10]
```diff
@@ -183,7 +183,7 @@ uint32_t CryptoMiniSat5::getFixedCountWithAssumptions(const stp::SATSolver::vec_
 
   // The assumptions are each single literals (corresponding to bits) that are true/false. 
   // so in the result they should be all be set 
-  assert(assigned >= assumps.size());
+  assert(static_cast<int>(assigned) >= assumps.size());
```
Comment (andrewvaughanj) [inline lib/Sat/CryptoMinisat5.cpp:186]: `assumps.size()` returns an `int` and `assigned` is an `unsigned int`; we know "by inspection" that `unsigned int` is "more correct" -- given this, it should be: `assert(assigned >= static_cast<unsigned int>(assumps.size()));`

File: lib/Sat/CryptoMinisat5.cpp (hunk 9 above)
Comment (Shatur) [reply lib/Sat/CryptoMinisat5.cpp:172]: I used `uint32_t` only because the return type of the function is marked as `uint32_t` and that value is returned from it.

File: lib/Sat/CryptoMinisat5.cpp (hunk 10 above)
Comment (Shatur) [reply lib/Sat/CryptoMinisat5.cpp:186]: Makes sense. I think that we can assume that `assumps.size()` will never return a negative value.

File: lib/Sat/CryptoMinisat5.cpp (hunk 9 above)
Comment (andrewvaughanj) [reply lib/Sat/CryptoMinisat5.cpp:172]: GOOD SPOT!!! You're totally correct!!!

File: lib/Sat/CryptoMinisat5.cpp (hunk 10 above)
Comment (andrewvaughanj) [reply lib/Sat/CryptoMinisat5.cpp:186]: So cast `assumps.size()` to `uint32_t` (and let's hope we never have more than 2^32 assumptions 🙈)

Comment (Shatur) [reply lib/Sat/CryptoMinisat5.cpp]: Done!

File: CMakeLists.txt [hunk 11]
```diff
@@ -304,33 +322,39 @@ if(APPLE)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
 endif()
 
-if (NOT MSVC)
-    add_cxx_flag_if_supported("-Wall")
-    add_cxx_flag_if_supported("-Wextra")
-    add_cxx_flag_if_supported("-Wunused")
-    add_cxx_flag_if_supported("-pedantic")
-    add_cxx_flag_if_supported("-Wsign-compare")
+set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```
Comment (andrewvaughanj) [inline CMakeLists.txt:325]: Given how MSVC handles PIC (i.e., it doesn't), I think we should move this into the `if (NOT MSVC)` block, unless you have any objections?

**Comment by andrewvaughanj** [comment]
One last comment from me (the one on `fPIC`) and then I think it looks good.

Have you tested that this "all works" for your purposes (apart from the message bits)?

File: CMakeLists.txt (hunk 11 above)
Comment (Shatur) [reply CMakeLists.txt:325]: This option does nothing automatically if MSVC is used. If you wish, I can move it under `if (NOT MSVC)`

**Comment by Shatur** [comment]
> Have you tested that this "all works" for your purposes (apart from the message bits)?

Yes!

File: CMakeLists.txt (hunk 11 above)
Comment (andrewvaughanj) [reply CMakeLists.txt:325]: Agreed, but it is a "nicer" change if we exchange `-fPIC` for `CMAKE_POSITION_INDEPENDENT_CODE`!

Comment (Shatur) [reply CMakeLists.txt:325]: No problem, will move!

Comment (Shatur) [reply CMakeLists.txt]: Done!

**Review by andrewvaughanj — APPROVED** [review]
Looks great! Thanks!

**Comment by andrewvaughanj** [comment]
Thanks, @Shatur!

**Comment by Shatur** [comment]
> apart from the message bits

Opened a separate PR: #411.
